### ISSUE TITLE
Environments for the pipeline

### ISSUE THREAD

**Issue by bsalehe** [cambiotraining/awd-pathogen-bioinformatics#11]
The following are conda environment names for the pipeline need to be created. Essentially, they are aimed for command line practicals.

- [x]  "**assembly**" - this will be used for running flye, medaka, rasusa, bakta, Mash
- [x]  "**typing**" - this will be used to run mlst, panaroo, IQ-TREE, and Figtree
- [x]  "**nextflow**" - for running AMR analysis with nf-core/funcscan
- [x]  "**checkm**" - for checking the quality of assembly

**Comment by tavareshugo** [comment]
These are all detailed in the [data & setup](https://github.com/cambiotraining/awd-pathogen-bioinformatics/blob/main/setup.md)
